project:
  type: website

website:
  title: "NZ Herald Poll of Polls"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - pipeline.qmd
      - about.qmd

format:
  html:
    theme: sandstone
    mainfont: "Source Sans Pro"
    monofont: "Source Code Pro"
    linkcolor: "#38A3D7"
    css: styles.css
    toc: true



